# https://github.com/probot/settings

branches:
    - name: master
      protection:
          enforce_admins: false
          required_pull_request_reviews:
              dismiss_stale_reviews: true
              require_code_owner_reviews: true
              required_approving_review_count: 1
          restrictions: null
          required_linear_history: true
          required_status_checks:
              strict: true

labels:
    - name: typo
      color: ee0701

    - name: dependencies
      color: 0366d6

    - name: enhancement
      color: 0e8a16

    - name: question
      color: cc317c

    - name: security
      color: ee0701

    - name: stale
      color: eeeeee

repository:
    allow_merge_commit: true
    allow_rebase_merge: true
    allow_squash_merge: true
    default_branch: master
    description:
        "Bartosz Milewski's 'Category Theory for Programmers' unofficial PDF and
        LaTeX sources"
    homepage: https://bartoszmilewski.com/2014/10/28/category-theory-for-programmers-the-preface/
    topics: pdf,haskell,scala,latex,cpp,functional-programming,ocaml,category-theory
    has_downloads: true
    has_issues: true
    has_pages: false
    has_projects: false
    has_wiki: false
    name: milewski-ctfp-pdf
    private: false
