@comment
@comment             **********************************************************
@setfilename         sicp
@settitle            Category Theory for Programmers
@comment             Unofficial Texinfo Format
@comment
@set utfversion      0.1
@set utfversiondate  September 2017
@comment
@comment             This file is licensed under a Creative Commons
@comment             Attribution-ShareAlike 4.0 International License
@comment             (http://creativecommons.org/licenses/by-sa/4.0/).
@comment
@comment             This is a Texinfo file with embedded LaTeX commands.
@comment             To compile it to PDF, enter `make' in current directory.
@comment             For more information about this file, see the text under
@comment             `@node UTF' below.
@comment
@comment             Various versions of sicp.texi and preformatted sicp.info
@comment             can be found at the following Web pages:
@comment
@comment                 http://www.neilvandyke.org/sicp-texi/
@comment                 http://sicpebook.wordpress.com/
@comment                 [add your own here]
@comment
@comment             **********************************************************

@comment HISTORY:
@comment
@comment * Version 1 (September, 2017) by Igal Tabachnik.
@comment   Based on the SICP PDF work of Andres Raba et al.
@comment   https://github.com/sarabander/sicp-pdf
@comment   

\frontmatter

\includepdf[scale=0.92]{coverpage.pdf}

\pagebreak

\vspace*{\fill}
\thispagestyle{empty}

\begin{small}
\begin{center}

@noindent
Category Theory for Programmers@*

@sp 1.0
@noindent
Bartosz Milewski@*

@sp 1.26
@noindent
Version @value{utfversion}, @value{utfversiondate}@*

@sp 1.6
@noindent
@image{fig/icons/cc, 3mm,,,.pdf}
@image{fig/icons/by, 3mm,,,.pdf}
@image{fig/icons/sa, 3mm,,,.pdf}

@sp 0.4
@noindent
This work is licensed under a Creative Commons@*
Attribution-ShareAlike 4.0 International License@*
(@url{http://creativecommons.org/licenses/by-sa/4.0/, @acronym{CC BY-SA 4.0}}).

@sp 1.26
@noindent
Converted to LaTeX from a series of blog posts by @url{https://bartoszmilewski.com/2014/10/28/category-theory-for-programmers-the-preface/, Bartosz Milewski}.@*
PDF compiled by @url{https://github.com/hmemcpy/milewski-ctfp-pdf, Igal Tabachnik}.@*

\end{center}
\end{small}

\pagebreak
\tableofcontents

@unnumbered Preface
@node    Preface

\subfile{content/0.0/Preface}

\mainmatter

\part{Part One}

\chapter{Category: The Essence of Composition}
\subfile{content/1.1/Category - The Essence of Composition}

\chapter{Types and Functions}
\subfile{content/1.2/Types and Functions}

\chapter{Categories Great and Small}
\subfile{content/1.3/Categories Great and Small}

\chapter{Kleisli Categories}
\subfile{content/1.4/Kleisli Categories}

\chapter{Products and Coproducts}
\subfile{content/1.5/Products and Coproducts}

\chapter{Simple Algebraic Data Types}
\subfile{content/1.6/Simple Algebraic Data Types}

@bye
