name: Prettier checks

on:
    pull_request:

jobs:
    prettier:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Install the Nix package manager
              uses: cachix/install-nix-action@v18

            - name: Checks
              run: nix run nixpkgs#nodePackages.prettier -- --check .
